<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the AuditLog connector object
 *
 */
trait AuditLogDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	private $id;    

	 /**
	 * @var string
	 *
	 
	 */
	private $action;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $actionId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $sourceId;    

	 /**
	 * @var string
	 *
	 
	 */
	private $sourceType;    

	 /**
	 * @var string
	 *
	 
	 */
	private $sourceLabel;    

	 /**
	 * @var string
	 *
	 
	 */
	private $changesDescription;    

	 /**
	 * @var string
	 *
	 
	 */
	private $ipAddress;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $createdAt;    

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return AuditLog
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

    

	/**
	 * Set action
	 *
	 * @param  string $action
	 * @return AuditLog
	 */
	public function setAction($action)
	{
		$this->action = $action;
		
		return $this;
	}
	
	/**
	 * Get action
	 *
	 * @return string
	 */
	public function getAction()
	{
		return $this->action;
	}

    

	/**
	 * Set actionId
	 *
	 * @param  integer $actionId
	 * @return AuditLog
	 */
	public function setActionId($actionId)
	{
		$this->actionId = $actionId;
		
		return $this;
	}
	
	/**
	 * Get actionId
	 *
	 * @return integer
	 */
	public function getActionId()
	{
		return $this->actionId;
	}

    

	/**
	 * Set sourceId
	 *
	 * @param  integer $sourceId
	 * @return AuditLog
	 */
	public function setSourceId($sourceId)
	{
		$this->sourceId = $sourceId;
		
		return $this;
	}
	
	/**
	 * Get sourceId
	 *
	 * @return integer
	 */
	public function getSourceId()
	{
		return $this->sourceId;
	}

    

	/**
	 * Set sourceType
	 *
	 * @param  string $sourceType
	 * @return AuditLog
	 */
	public function setSourceType($sourceType)
	{
		$this->sourceType = $sourceType;
		
		return $this;
	}
	
	/**
	 * Get sourceType
	 *
	 * @return string
	 */
	public function getSourceType()
	{
		return $this->sourceType;
	}

    

	/**
	 * Set sourceLabel
	 *
	 * @param  string $sourceLabel
	 * @return AuditLog
	 */
	public function setSourceLabel($sourceLabel)
	{
		$this->sourceLabel = $sourceLabel;
		
		return $this;
	}
	
	/**
	 * Get sourceLabel
	 *
	 * @return string
	 */
	public function getSourceLabel()
	{
		return $this->sourceLabel;
	}

    

	/**
	 * Set changesDescription
	 *
	 * @param  string $changesDescription
	 * @return AuditLog
	 */
	public function setChangesDescription($changesDescription)
	{
		$this->changesDescription = $changesDescription;
		
		return $this;
	}
	
	/**
	 * Get changesDescription
	 *
	 * @return string
	 */
	public function getChangesDescription()
	{
		return $this->changesDescription;
	}

    

	/**
	 * Set ipAddress
	 *
	 * @param  string $ipAddress
	 * @return AuditLog
	 */
	public function setIpAddress($ipAddress)
	{
		$this->ipAddress = $ipAddress;
		
		return $this;
	}
	
	/**
	 * Get ipAddress
	 *
	 * @return string
	 */
	public function getIpAddress()
	{
		return $this->ipAddress;
	}

    

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return AuditLog
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}
	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

}