<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Brand connector object
 *
 */
trait BrandDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $name;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $brandUrl;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $hasHelpCenter;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $helpCenterState;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $active;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $default;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $logo;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $ticketFromIds;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdId;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $subdomain;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $hostMapping;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $signatureTemplate;
	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Brand
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return Brand
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}	
    

	
	/**
	 * Get brandUrl
	 *
	 * @return string
	 */
	public function getBrandUrl()
	{
		return $this->brandUrl;
	}

	/**
	 * Set brandUrl
	 *
	 * @param  string $brandUrl
	 * @return Brand
	 */
	public function setBrandUrl($brandUrl)
	{
		$this->brandUrl = $brandUrl;
		
		return $this;
	}	
    

	
	/**
	 * Get hasHelpCenter
	 *
	 * @return blob
	 */
	public function getHasHelpCenter()
	{
		return $this->hasHelpCenter;
	}

	/**
	 * Set hasHelpCenter
	 *
	 * @param  blob $hasHelpCenter
	 * @return Brand
	 */
	public function setHasHelpCenter($hasHelpCenter)
	{
		$this->hasHelpCenter = $hasHelpCenter;
		
		return $this;
	}	
    

	
	/**
	 * Get helpCenterState
	 *
	 * @return string
	 */
	public function getHelpCenterState()
	{
		return $this->helpCenterState;
	}

	/**
	 * Set helpCenterState
	 *
	 * @param  string $helpCenterState
	 * @return Brand
	 */
	public function setHelpCenterState($helpCenterState)
	{
		$this->helpCenterState = $helpCenterState;
		
		return $this;
	}	
    

	
	/**
	 * Get active
	 *
	 * @return blob
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Set active
	 *
	 * @param  blob $active
	 * @return Brand
	 */
	public function setActive($active)
	{
		$this->active = $active;
		
		return $this;
	}	
    

	
	/**
	 * Get default
	 *
	 * @return blob
	 */
	public function getDefault()
	{
		return $this->default;
	}

	/**
	 * Set default
	 *
	 * @param  blob $default
	 * @return Brand
	 */
	public function setDefault($default)
	{
		$this->default = $default;
		
		return $this;
	}	
    

	
	/**
	 * Get logo
	 *
	 * @return blob
	 */
	public function getLogo()
	{
		return $this->logo;
	}

	/**
	 * Set logo
	 *
	 * @param  blob $logo
	 * @return Brand
	 */
	public function setLogo($logo)
	{
		$this->logo = $logo;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Brand
	 */
	public function addTicketFromIds($elem)
	{
		$this->ticketFromIds[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasTicketFromIds($elem)
	{
		return in_array($elem, $this->ticketFromIds);
	}
	
	
	/**
	 * Get ticketFromIds
	 *
	 * @return Array
	 */
	public function getTicketFromIds()
	{
		return $this->ticketFromIds;
	}

	/**
	 * Set ticketFromIds
	 *
	 * @param  Array $ticketFromIds
	 * @return Brand
	 */
	public function setTicketFromIds($ticketFromIds)
	{
		$this->ticketFromIds = $ticketFromIds;
		
		return $this;
	}	
    

	
	/**
	 * Get createdId
	 *
	 * @return datetime
	 */
	public function getCreatedId()
	{
		return $this->createdId;
	}

	/**
	 * Set createdId
	 *
	 * @param  datetime $createdId
	 * @return Brand
	 */
	public function setCreatedId($createdId)
	{
		$this->createdId = $createdId;
		
		return $this;
	}	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Brand
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
    

	
	/**
	 * Get subdomain
	 *
	 * @return string
	 */
	public function getSubdomain()
	{
		return $this->subdomain;
	}

	/**
	 * Set subdomain
	 *
	 * @param  string $subdomain
	 * @return Brand
	 */
	public function setSubdomain($subdomain)
	{
		$this->subdomain = $subdomain;
		
		return $this;
	}	
    

	
	/**
	 * Get hostMapping
	 *
	 * @return string
	 */
	public function getHostMapping()
	{
		return $this->hostMapping;
	}

	/**
	 * Set hostMapping
	 *
	 * @param  string $hostMapping
	 * @return Brand
	 */
	public function setHostMapping($hostMapping)
	{
		$this->hostMapping = $hostMapping;
		
		return $this;
	}	
    

	
	/**
	 * Get signatureTemplate
	 *
	 * @return string
	 */
	public function getSignatureTemplate()
	{
		return $this->signatureTemplate;
	}

	/**
	 * Set signatureTemplate
	 *
	 * @param  string $signatureTemplate
	 * @return Brand
	 */
	public function setSignatureTemplate($signatureTemplate)
	{
		$this->signatureTemplate = $signatureTemplate;
		
		return $this;
	}	
}