<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Group connector object
 *
 */
trait GroupDefinition
{    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $name;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $deleted;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $url;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdAt;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return Group
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}	
    

	
	/**
	 * Get deleted
	 *
	 * @return blob
	 */
	public function getDeleted()
	{
		return $this->deleted;
	}

	/**
	 * Set deleted
	 *
	 * @param  blob $deleted
	 * @return Group
	 */
	public function setDeleted($deleted)
	{
		$this->deleted = $deleted;
		
		return $this;
	}	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Group
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return Group
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}	
    

	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return Group
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Group
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
}