<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the JobStatus connector object
 *
 */
trait JobStatusDefinition
{    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $url;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $total;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $progress;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $status;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $message;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $results;
	
    

	
	/**
	 * Get id
	 *
	 * @return string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  string $id
	 * @return JobStatus
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return JobStatus
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}	
    

	
	/**
	 * Get total
	 *
	 * @return integer
	 */
	public function getTotal()
	{
		return $this->total;
	}

	/**
	 * Set total
	 *
	 * @param  integer $total
	 * @return JobStatus
	 */
	public function setTotal($total)
	{
		$this->total = $total;
		
		return $this;
	}	
    

	
	/**
	 * Get progress
	 *
	 * @return integer
	 */
	public function getProgress()
	{
		return $this->progress;
	}

	/**
	 * Set progress
	 *
	 * @param  integer $progress
	 * @return JobStatus
	 */
	public function setProgress($progress)
	{
		$this->progress = $progress;
		
		return $this;
	}	
    

	
	/**
	 * Get status
	 *
	 * @return string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set status
	 *
	 * @param  string $status
	 * @return JobStatus
	 */
	public function setStatus($status)
	{
		$this->status = $status;
		
		return $this;
	}	
    

	
	/**
	 * Get message
	 *
	 * @return string
	 */
	public function getMessage()
	{
		return $this->message;
	}

	/**
	 * Set message
	 *
	 * @param  string $message
	 * @return JobStatus
	 */
	public function setMessage($message)
	{
		$this->message = $message;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return JobStatus
	 */
	public function addResults($elem)
	{
		$this->results[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasResults($elem)
	{
		return in_array($elem, $this->results);
	}
	
	
	/**
	 * Get results
	 *
	 * @return Array
	 */
	public function getResults()
	{
		return $this->results;
	}

	/**
	 * Set results
	 *
	 * @param  Array $results
	 * @return JobStatus
	 */
	public function setResults($results)
	{
		$this->results = $results;
		
		return $this;
	}	
}