<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Macro connector object
 *
 */
trait MacroDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	private $id;    

	 /**
	 * @var string
	 *
	 
	 */
	private $title;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $active;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $position;    

	 /**
	 * @var string
	 *
	 
	 */
	private $restriction;    

	 /**
	 * @var string
	 *
	 
	 */
	private $actions;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $createdAt;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $updatedAt;    

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Macro
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

    

	/**
	 * Set title
	 *
	 * @param  string $title
	 * @return Macro
	 */
	public function setTitle($title)
	{
		$this->title = $title;
		
		return $this;
	}
	
	/**
	 * Get title
	 *
	 * @return string
	 */
	public function getTitle()
	{
		return $this->title;
	}

    

	/**
	 * Set active
	 *
	 * @param  integer $active
	 * @return Macro
	 */
	public function setActive($active)
	{
		$this->active = $active;
		
		return $this;
	}
	
	/**
	 * Get active
	 *
	 * @return integer
	 */
	public function getActive()
	{
		return $this->active;
	}

    

	/**
	 * Set position
	 *
	 * @param  integer $position
	 * @return Macro
	 */
	public function setPosition($position)
	{
		$this->position = $position;
		
		return $this;
	}
	
	/**
	 * Get position
	 *
	 * @return integer
	 */
	public function getPosition()
	{
		return $this->position;
	}

    

	/**
	 * Set restriction
	 *
	 * @param  string $restriction
	 * @return Macro
	 */
	public function setRestriction($restriction)
	{
		$this->restriction = $restriction;
		
		return $this;
	}
	
	/**
	 * Get restriction
	 *
	 * @return string
	 */
	public function getRestriction()
	{
		return $this->restriction;
	}

    

	/**
	 * Set actions
	 *
	 * @param  string $actions
	 * @return Macro
	 */
	public function setActions($actions)
	{
		$this->actions = $actions;
		
		return $this;
	}
	
	/**
	 * Get actions
	 *
	 * @return string
	 */
	public function getActions()
	{
		return $this->actions;
	}

    

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return Macro
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}
	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

    

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Macro
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}
	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

}