<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Organization connector object
 *
 */
trait OrganizationDefinition
{    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $domainNames;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $details;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $notes;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $groupId;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $sharedTickets;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $sharedComments;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $tags;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $organizationFields;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $url;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $externalId;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $name;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdAt;
	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Organization
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Organization
	 */
	public function addDomainNames($elem)
	{
		$this->domainNames[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasDomainNames($elem)
	{
		return in_array($elem, $this->domainNames);
	}
	
	
	/**
	 * Get domainNames
	 *
	 * @return Array
	 */
	public function getDomainNames()
	{
		return $this->domainNames;
	}

	/**
	 * Set domainNames
	 *
	 * @param  Array $domainNames
	 * @return Organization
	 */
	public function setDomainNames($domainNames)
	{
		$this->domainNames = $domainNames;
		
		return $this;
	}	
    

	
	/**
	 * Get details
	 *
	 * @return string
	 */
	public function getDetails()
	{
		return $this->details;
	}

	/**
	 * Set details
	 *
	 * @param  string $details
	 * @return Organization
	 */
	public function setDetails($details)
	{
		$this->details = $details;
		
		return $this;
	}	
    

	
	/**
	 * Get notes
	 *
	 * @return string
	 */
	public function getNotes()
	{
		return $this->notes;
	}

	/**
	 * Set notes
	 *
	 * @param  string $notes
	 * @return Organization
	 */
	public function setNotes($notes)
	{
		$this->notes = $notes;
		
		return $this;
	}	
    

	
	/**
	 * Get groupId
	 *
	 * @return integer
	 */
	public function getGroupId()
	{
		return $this->groupId;
	}

	/**
	 * Set groupId
	 *
	 * @param  integer $groupId
	 * @return Organization
	 */
	public function setGroupId($groupId)
	{
		$this->groupId = $groupId;
		
		return $this;
	}	
    

	
	/**
	 * Get sharedTickets
	 *
	 * @return blob
	 */
	public function getSharedTickets()
	{
		return $this->sharedTickets;
	}

	/**
	 * Set sharedTickets
	 *
	 * @param  blob $sharedTickets
	 * @return Organization
	 */
	public function setSharedTickets($sharedTickets)
	{
		$this->sharedTickets = $sharedTickets;
		
		return $this;
	}	
    

	
	/**
	 * Get sharedComments
	 *
	 * @return blob
	 */
	public function getSharedComments()
	{
		return $this->sharedComments;
	}

	/**
	 * Set sharedComments
	 *
	 * @param  blob $sharedComments
	 * @return Organization
	 */
	public function setSharedComments($sharedComments)
	{
		$this->sharedComments = $sharedComments;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Organization
	 */
	public function addTags($elem)
	{
		$this->tags[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasTags($elem)
	{
		return in_array($elem, $this->tags);
	}
	
	
	/**
	 * Get tags
	 *
	 * @return Array
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * Set tags
	 *
	 * @param  Array $tags
	 * @return Organization
	 */
	public function setTags($tags)
	{
		$this->tags = $tags;
		
		return $this;
	}	
    

	
	/**
	 * Get organizationFields
	 *
	 * @return Object
	 */
	public function getOrganizationFields()
	{
		return $this->organizationFields;
	}

	/**
	 * Set organizationFields
	 *
	 * @param  Object $organizationFields
	 * @return Organization
	 */
	public function setOrganizationFields($organizationFields)
	{
		$this->organizationFields = $organizationFields;
		
		return $this;
	}	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Organization
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return Organization
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}	
    

	
	/**
	 * Get externalId
	 *
	 * @return string
	 */
	public function getExternalId()
	{
		return $this->externalId;
	}

	/**
	 * Set externalId
	 *
	 * @param  string $externalId
	 * @return Organization
	 */
	public function setExternalId($externalId)
	{
		$this->externalId = $externalId;
		
		return $this;
	}	
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return Organization
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}	
    

	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return Organization
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}	
}