<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the OrganizationMemberships connector object
 *
 */
trait OrganizationMembershipsDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	private $id;    

	 /**
	 * @var string
	 *
	 
	 */
	private $url;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $userId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $organizationId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $default;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $createdAt;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $updatedAt;    

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return OrganizationMemberships
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

    

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return OrganizationMemberships
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}
	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

    

	/**
	 * Set userId
	 *
	 * @param  integer $userId
	 * @return OrganizationMemberships
	 */
	public function setUserId($userId)
	{
		$this->userId = $userId;
		
		return $this;
	}
	
	/**
	 * Get userId
	 *
	 * @return integer
	 */
	public function getUserId()
	{
		return $this->userId;
	}

    

	/**
	 * Set organizationId
	 *
	 * @param  integer $organizationId
	 * @return OrganizationMemberships
	 */
	public function setOrganizationId($organizationId)
	{
		$this->organizationId = $organizationId;
		
		return $this;
	}
	
	/**
	 * Get organizationId
	 *
	 * @return integer
	 */
	public function getOrganizationId()
	{
		return $this->organizationId;
	}

    

	/**
	 * Set default
	 *
	 * @param  integer $default
	 * @return OrganizationMemberships
	 */
	public function setDefault($default)
	{
		$this->default = $default;
		
		return $this;
	}
	
	/**
	 * Get default
	 *
	 * @return integer
	 */
	public function getDefault()
	{
		return $this->default;
	}

    

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return OrganizationMemberships
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}
	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

    

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return OrganizationMemberships
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}
	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

}