<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Request connector object
 *
 */
trait RequestDefinition
{    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $customFields;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $organizationId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $requesterId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $assigneeId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $groupId;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $collaboratorIds;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $via;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $dueAt;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $canBeSolvedByMe;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $solved;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $ticketFromId;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdAt;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $recepient;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $followupSourceId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $url;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $subject;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $description;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $status;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $priority;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $type;
	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Request
	 */
	public function addCustomFields($elem)
	{
		$this->customFields[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasCustomFields($elem)
	{
		return in_array($elem, $this->customFields);
	}
	
	
	/**
	 * Get customFields
	 *
	 * @return Array
	 */
	public function getCustomFields()
	{
		return $this->customFields;
	}

	/**
	 * Set customFields
	 *
	 * @param  Array $customFields
	 * @return Request
	 */
	public function setCustomFields($customFields)
	{
		$this->customFields = $customFields;
		
		return $this;
	}	
    

	
	/**
	 * Get organizationId
	 *
	 * @return integer
	 */
	public function getOrganizationId()
	{
		return $this->organizationId;
	}

	/**
	 * Set organizationId
	 *
	 * @param  integer $organizationId
	 * @return Request
	 */
	public function setOrganizationId($organizationId)
	{
		$this->organizationId = $organizationId;
		
		return $this;
	}	
    

	
	/**
	 * Get requesterId
	 *
	 * @return integer
	 */
	public function getRequesterId()
	{
		return $this->requesterId;
	}

	/**
	 * Set requesterId
	 *
	 * @param  integer $requesterId
	 * @return Request
	 */
	public function setRequesterId($requesterId)
	{
		$this->requesterId = $requesterId;
		
		return $this;
	}	
    

	
	/**
	 * Get assigneeId
	 *
	 * @return integer
	 */
	public function getAssigneeId()
	{
		return $this->assigneeId;
	}

	/**
	 * Set assigneeId
	 *
	 * @param  integer $assigneeId
	 * @return Request
	 */
	public function setAssigneeId($assigneeId)
	{
		$this->assigneeId = $assigneeId;
		
		return $this;
	}	
    

	
	/**
	 * Get groupId
	 *
	 * @return integer
	 */
	public function getGroupId()
	{
		return $this->groupId;
	}

	/**
	 * Set groupId
	 *
	 * @param  integer $groupId
	 * @return Request
	 */
	public function setGroupId($groupId)
	{
		$this->groupId = $groupId;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Request
	 */
	public function addCollaboratorIds($elem)
	{
		$this->collaboratorIds[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasCollaboratorIds($elem)
	{
		return in_array($elem, $this->collaboratorIds);
	}
	
	
	/**
	 * Get collaboratorIds
	 *
	 * @return Array
	 */
	public function getCollaboratorIds()
	{
		return $this->collaboratorIds;
	}

	/**
	 * Set collaboratorIds
	 *
	 * @param  Array $collaboratorIds
	 * @return Request
	 */
	public function setCollaboratorIds($collaboratorIds)
	{
		$this->collaboratorIds = $collaboratorIds;
		
		return $this;
	}	
    

	
	/**
	 * Get via
	 *
	 * @return Object
	 */
	public function getVia()
	{
		return $this->via;
	}

	/**
	 * Set via
	 *
	 * @param  Object $via
	 * @return Request
	 */
	public function setVia($via)
	{
		$this->via = $via;
		
		return $this;
	}	
    

	
	/**
	 * Get dueAt
	 *
	 * @return datetime
	 */
	public function getDueAt()
	{
		return $this->dueAt;
	}

	/**
	 * Set dueAt
	 *
	 * @param  datetime $dueAt
	 * @return Request
	 */
	public function setDueAt($dueAt)
	{
		$this->dueAt = $dueAt;
		
		return $this;
	}	
    

	
	/**
	 * Get canBeSolvedByMe
	 *
	 * @return blob
	 */
	public function getCanBeSolvedByMe()
	{
		return $this->canBeSolvedByMe;
	}

	/**
	 * Set canBeSolvedByMe
	 *
	 * @param  blob $canBeSolvedByMe
	 * @return Request
	 */
	public function setCanBeSolvedByMe($canBeSolvedByMe)
	{
		$this->canBeSolvedByMe = $canBeSolvedByMe;
		
		return $this;
	}	
    

	
	/**
	 * Get solved
	 *
	 * @return blob
	 */
	public function getSolved()
	{
		return $this->solved;
	}

	/**
	 * Set solved
	 *
	 * @param  blob $solved
	 * @return Request
	 */
	public function setSolved($solved)
	{
		$this->solved = $solved;
		
		return $this;
	}	
    

	
	/**
	 * Get ticketFromId
	 *
	 * @return integer
	 */
	public function getTicketFromId()
	{
		return $this->ticketFromId;
	}

	/**
	 * Set ticketFromId
	 *
	 * @param  integer $ticketFromId
	 * @return Request
	 */
	public function setTicketFromId($ticketFromId)
	{
		$this->ticketFromId = $ticketFromId;
		
		return $this;
	}	
    

	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return Request
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Request
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
    

	
	/**
	 * Get recepient
	 *
	 * @return string
	 */
	public function getRecepient()
	{
		return $this->recepient;
	}

	/**
	 * Set recepient
	 *
	 * @param  string $recepient
	 * @return Request
	 */
	public function setRecepient($recepient)
	{
		$this->recepient = $recepient;
		
		return $this;
	}	
    

	
	/**
	 * Get followupSourceId
	 *
	 * @return integer
	 */
	public function getFollowupSourceId()
	{
		return $this->followupSourceId;
	}

	/**
	 * Set followupSourceId
	 *
	 * @param  integer $followupSourceId
	 * @return Request
	 */
	public function setFollowupSourceId($followupSourceId)
	{
		$this->followupSourceId = $followupSourceId;
		
		return $this;
	}	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Request
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return Request
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}	
    

	
	/**
	 * Get subject
	 *
	 * @return string
	 */
	public function getSubject()
	{
		return $this->subject;
	}

	/**
	 * Set subject
	 *
	 * @param  string $subject
	 * @return Request
	 */
	public function setSubject($subject)
	{
		$this->subject = $subject;
		
		return $this;
	}	
    

	
	/**
	 * Get description
	 *
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set description
	 *
	 * @param  string $description
	 * @return Request
	 */
	public function setDescription($description)
	{
		$this->description = $description;
		
		return $this;
	}	
    

	
	/**
	 * Get status
	 *
	 * @return string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set status
	 *
	 * @param  string $status
	 * @return Request
	 */
	public function setStatus($status)
	{
		$this->status = $status;
		
		return $this;
	}	
    

	
	/**
	 * Get priority
	 *
	 * @return Object
	 */
	public function getPriority()
	{
		return $this->priority;
	}

	/**
	 * Set priority
	 *
	 * @param  Object $priority
	 * @return Request
	 */
	public function setPriority($priority)
	{
		$this->priority = $priority;
		
		return $this;
	}	
    

	
	/**
	 * Get type
	 *
	 * @return string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Set type
	 *
	 * @param  string $type
	 * @return Request
	 */
	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}	
}