<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the SatisfactionRating connector object
 *
 */
trait SatisfactionRatingDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	private $id;    

	 /**
	 * @var string
	 *
	 
	 */
	private $url;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $assigneeId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $groupId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $requesterId;    

	 /**
	 * @var integer
	 *
	 
	 */
	private $ticketId;    

	 /**
	 * @var string
	 *
	 
	 */
	private $score;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $createdAt;    

	 /**
	 * @var datetime
	 *
	 
	 */
	private $updatedAt;    

	 /**
	 * @var string
	 *
	 
	 */
	private $comment;    

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return SatisfactionRating
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

    

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return SatisfactionRating
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}
	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

    

	/**
	 * Set assigneeId
	 *
	 * @param  integer $assigneeId
	 * @return SatisfactionRating
	 */
	public function setAssigneeId($assigneeId)
	{
		$this->assigneeId = $assigneeId;
		
		return $this;
	}
	
	/**
	 * Get assigneeId
	 *
	 * @return integer
	 */
	public function getAssigneeId()
	{
		return $this->assigneeId;
	}

    

	/**
	 * Set groupId
	 *
	 * @param  integer $groupId
	 * @return SatisfactionRating
	 */
	public function setGroupId($groupId)
	{
		$this->groupId = $groupId;
		
		return $this;
	}
	
	/**
	 * Get groupId
	 *
	 * @return integer
	 */
	public function getGroupId()
	{
		return $this->groupId;
	}

    

	/**
	 * Set requesterId
	 *
	 * @param  integer $requesterId
	 * @return SatisfactionRating
	 */
	public function setRequesterId($requesterId)
	{
		$this->requesterId = $requesterId;
		
		return $this;
	}
	
	/**
	 * Get requesterId
	 *
	 * @return integer
	 */
	public function getRequesterId()
	{
		return $this->requesterId;
	}

    

	/**
	 * Set ticketId
	 *
	 * @param  integer $ticketId
	 * @return SatisfactionRating
	 */
	public function setTicketId($ticketId)
	{
		$this->ticketId = $ticketId;
		
		return $this;
	}
	
	/**
	 * Get ticketId
	 *
	 * @return integer
	 */
	public function getTicketId()
	{
		return $this->ticketId;
	}

    

	/**
	 * Set score
	 *
	 * @param  string $score
	 * @return SatisfactionRating
	 */
	public function setScore($score)
	{
		$this->score = $score;
		
		return $this;
	}
	
	/**
	 * Get score
	 *
	 * @return string
	 */
	public function getScore()
	{
		return $this->score;
	}

    

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return SatisfactionRating
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}
	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

    

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return SatisfactionRating
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}
	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

    

	/**
	 * Set comment
	 *
	 * @param  string $comment
	 * @return SatisfactionRating
	 */
	public function setComment($comment)
	{
		$this->comment = $comment;
		
		return $this;
	}
	
	/**
	 * Get comment
	 *
	 * @return string
	 */
	public function getComment()
	{
		return $this->comment;
	}

}