<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Search connector object
 *
 */
trait SearchDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $count;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $nextPage;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $prevPage;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $results;
	
    

	
	/**
	 * Get count
	 *
	 * @return integer
	 */
	public function getCount()
	{
		return $this->count;
	}

	/**
	 * Set count
	 *
	 * @param  integer $count
	 * @return Search
	 */
	public function setCount($count)
	{
		$this->count = $count;
		
		return $this;
	}	
    

	
	/**
	 * Get nextPage
	 *
	 * @return string
	 */
	public function getNextPage()
	{
		return $this->nextPage;
	}

	/**
	 * Set nextPage
	 *
	 * @param  string $nextPage
	 * @return Search
	 */
	public function setNextPage($nextPage)
	{
		$this->nextPage = $nextPage;
		
		return $this;
	}	
    

	
	/**
	 * Get prevPage
	 *
	 * @return string
	 */
	public function getPrevPage()
	{
		return $this->prevPage;
	}

	/**
	 * Set prevPage
	 *
	 * @param  string $prevPage
	 * @return Search
	 */
	public function setPrevPage($prevPage)
	{
		$this->prevPage = $prevPage;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Search
	 */
	public function addResults($elem)
	{
		$this->results[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasResults($elem)
	{
		return in_array($elem, $this->results);
	}
	
	
	/**
	 * Get results
	 *
	 * @return Array
	 */
	public function getResults()
	{
		return $this->results;
	}

	/**
	 * Set results
	 *
	 * @param  Array $results
	 * @return Search
	 */
	public function setResults($results)
	{
		$this->results = $results;
		
		return $this;
	}	
}