<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Search connector object
 *
 */
trait SearchDefinition
{    

	 /**
	 * @var integer
	 *
	 
	 */
	private $count;    

	 /**
	 * @var string
	 *
	 
	 */
	private $nextPage;    

	 /**
	 * @var string
	 *
	 
	 */
	private $prevPage;    

	 /**
	 * @var string
	 *
	 
	 */
	private $results;    

	/**
	 * Set count
	 *
	 * @param  integer $count
	 * @return Search
	 */
	public function setCount($count)
	{
		$this->count = $count;
		
		return $this;
	}
	
	/**
	 * Get count
	 *
	 * @return integer
	 */
	public function getCount()
	{
		return $this->count;
	}

    

	/**
	 * Set nextPage
	 *
	 * @param  string $nextPage
	 * @return Search
	 */
	public function setNextPage($nextPage)
	{
		$this->nextPage = $nextPage;
		
		return $this;
	}
	
	/**
	 * Get nextPage
	 *
	 * @return string
	 */
	public function getNextPage()
	{
		return $this->nextPage;
	}

    

	/**
	 * Set prevPage
	 *
	 * @param  string $prevPage
	 * @return Search
	 */
	public function setPrevPage($prevPage)
	{
		$this->prevPage = $prevPage;
		
		return $this;
	}
	
	/**
	 * Get prevPage
	 *
	 * @return string
	 */
	public function getPrevPage()
	{
		return $this->prevPage;
	}

    

	/**
	 * Set results
	 *
	 * @param  string $results
	 * @return Search
	 */
	public function setResults($results)
	{
		$this->results = $results;
		
		return $this;
	}
	
	/**
	 * Get results
	 *
	 * @return string
	 */
	public function getResults()
	{
		return $this->results;
	}

}