<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Ticket connector object
 *
 */
trait TicketDefinition
{    


	private $id;    


	private $url;    


	private $externalId;    


	private $type;    


	private $subject;    


	private $rawSubject;    


	private $description;    


	private $priority;    


	private $status;    


	private $recipient;    


	private $requesterId;    


	private $submitterId;    


	private $assigneeId;    


	private $organizationId;    


	private $groupId;    


	private $collaboratorIds;    


	private $forumTopicId;    


	private $problemId;    


	private $hasIncidents;    


	private $dueAt;    


	private $tags;    


	private $via;    


	private $customFields;    


	private $satisfactionRating;    


	private $sharingAgreementIds;    


	private $followupIds;    


	private $ticketFormId;    


	private $brandId;    


	private $allowChannelback;    


	private $isPublic;    


	private $createdAt;    


	private $updatedAt;    

	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	public function getId()
	{
		return $this->id;
	}
    

	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}
	
	public function getUrl()
	{
		return $this->url;
	}
    

	public function setExternalId($externalId)
	{
		$this->externalId = $externalId;
		
		return $this;
	}
	
	public function getExternalId()
	{
		return $this->externalId;
	}
    

	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}
	
	public function getType()
	{
		return $this->type;
	}
    

	public function setSubject($subject)
	{
		$this->subject = $subject;
		
		return $this;
	}
	
	public function getSubject()
	{
		return $this->subject;
	}
    

	public function setRawSubject($rawSubject)
	{
		$this->rawSubject = $rawSubject;
		
		return $this;
	}
	
	public function getRawSubject()
	{
		return $this->rawSubject;
	}
    

	public function setDescription($description)
	{
		$this->description = $description;
		
		return $this;
	}
	
	public function getDescription()
	{
		return $this->description;
	}
    

	public function setPriority($priority)
	{
		$this->priority = $priority;
		
		return $this;
	}
	
	public function getPriority()
	{
		return $this->priority;
	}
    

	public function setStatus($status)
	{
		$this->status = $status;
		
		return $this;
	}
	
	public function getStatus()
	{
		return $this->status;
	}
    

	public function setRecipient($recipient)
	{
		$this->recipient = $recipient;
		
		return $this;
	}
	
	public function getRecipient()
	{
		return $this->recipient;
	}
    

	public function setRequesterId($requesterId)
	{
		$this->requesterId = $requesterId;
		
		return $this;
	}
	
	public function getRequesterId()
	{
		return $this->requesterId;
	}
    

	public function setSubmitterId($submitterId)
	{
		$this->submitterId = $submitterId;
		
		return $this;
	}
	
	public function getSubmitterId()
	{
		return $this->submitterId;
	}
    

	public function setAssigneeId($assigneeId)
	{
		$this->assigneeId = $assigneeId;
		
		return $this;
	}
	
	public function getAssigneeId()
	{
		return $this->assigneeId;
	}
    

	public function setOrganizationId($organizationId)
	{
		$this->organizationId = $organizationId;
		
		return $this;
	}
	
	public function getOrganizationId()
	{
		return $this->organizationId;
	}
    

	public function setGroupId($groupId)
	{
		$this->groupId = $groupId;
		
		return $this;
	}
	
	public function getGroupId()
	{
		return $this->groupId;
	}
    

	public function setCollaboratorIds($collaboratorIds)
	{
		$this->collaboratorIds = $collaboratorIds;
		
		return $this;
	}
	
	public function getCollaboratorIds()
	{
		return $this->collaboratorIds;
	}
    

	public function setForumTopicId($forumTopicId)
	{
		$this->forumTopicId = $forumTopicId;
		
		return $this;
	}
	
	public function getForumTopicId()
	{
		return $this->forumTopicId;
	}
    

	public function setProblemId($problemId)
	{
		$this->problemId = $problemId;
		
		return $this;
	}
	
	public function getProblemId()
	{
		return $this->problemId;
	}
    

	public function setHasIncidents($hasIncidents)
	{
		$this->hasIncidents = $hasIncidents;
		
		return $this;
	}
	
	public function getHasIncidents()
	{
		return $this->hasIncidents;
	}
    

	public function setDueAt($dueAt)
	{
		$this->dueAt = $dueAt;
		
		return $this;
	}
	
	public function getDueAt()
	{
		return $this->dueAt;
	}
    

	public function setTags($tags)
	{
		$this->tags = $tags;
		
		return $this;
	}
	
	public function getTags()
	{
		return $this->tags;
	}
    

	public function setVia($via)
	{
		$this->via = $via;
		
		return $this;
	}
	
	public function getVia()
	{
		return $this->via;
	}
    

	public function setCustomFields($customFields)
	{
		$this->customFields = $customFields;
		
		return $this;
	}
	
	public function getCustomFields()
	{
		return $this->customFields;
	}
    

	public function setSatisfactionRating($satisfactionRating)
	{
		$this->satisfactionRating = $satisfactionRating;
		
		return $this;
	}
	
	public function getSatisfactionRating()
	{
		return $this->satisfactionRating;
	}
    

	public function setSharingAgreementIds($sharingAgreementIds)
	{
		$this->sharingAgreementIds = $sharingAgreementIds;
		
		return $this;
	}
	
	public function getSharingAgreementIds()
	{
		return $this->sharingAgreementIds;
	}
    

	public function setFollowupIds($followupIds)
	{
		$this->followupIds = $followupIds;
		
		return $this;
	}
	
	public function getFollowupIds()
	{
		return $this->followupIds;
	}
    

	public function setTicketFormId($ticketFormId)
	{
		$this->ticketFormId = $ticketFormId;
		
		return $this;
	}
	
	public function getTicketFormId()
	{
		return $this->ticketFormId;
	}
    

	public function setBrandId($brandId)
	{
		$this->brandId = $brandId;
		
		return $this;
	}
	
	public function getBrandId()
	{
		return $this->brandId;
	}
    

	public function setAllowChannelback($allowChannelback)
	{
		$this->allowChannelback = $allowChannelback;
		
		return $this;
	}
	
	public function getAllowChannelback()
	{
		return $this->allowChannelback;
	}
    

	public function setIsPublic($isPublic)
	{
		$this->isPublic = $isPublic;
		
		return $this;
	}
	
	public function getIsPublic()
	{
		return $this->isPublic;
	}
    

	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}
	
	public function getCreatedAt()
	{
		return $this->createdAt;
	}
    

	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}
	
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}
}