<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the Ticket connector object
 *
 */
trait TicketDefinition
{    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $externalId;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $type;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $subject;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $rawSubject;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $description;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $priority;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $status;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $recipient;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $requesterId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $submitterId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $assigneeId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $organizationId;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $collaboratorIds;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $forumTopicId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $problemId;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $hasIncidents;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $dueAt;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $tags;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $via;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $customFields;
	
    

	 /**
	 * @var Object
	 *
	 
	 */
	
	private $satisfactionRating;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $sharingAgreementIds;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $followupIds;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $ticketFormId;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $brandId;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $allowChannelback;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $isPublic;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdAt;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	
	/**
	 * Get externalId
	 *
	 * @return string
	 */
	public function getExternalId()
	{
		return $this->externalId;
	}

	/**
	 * Set externalId
	 *
	 * @param  string $externalId
	 * @return Ticket
	 */
	public function setExternalId($externalId)
	{
		$this->externalId = $externalId;
		
		return $this;
	}	
    

	
	/**
	 * Get type
	 *
	 * @return string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Set type
	 *
	 * @param  string $type
	 * @return Ticket
	 */
	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}	
    

	
	/**
	 * Get subject
	 *
	 * @return string
	 */
	public function getSubject()
	{
		return $this->subject;
	}

	/**
	 * Set subject
	 *
	 * @param  string $subject
	 * @return Ticket
	 */
	public function setSubject($subject)
	{
		$this->subject = $subject;
		
		return $this;
	}	
    

	
	/**
	 * Get rawSubject
	 *
	 * @return string
	 */
	public function getRawSubject()
	{
		return $this->rawSubject;
	}

	/**
	 * Set rawSubject
	 *
	 * @param  string $rawSubject
	 * @return Ticket
	 */
	public function setRawSubject($rawSubject)
	{
		$this->rawSubject = $rawSubject;
		
		return $this;
	}	
    

	
	/**
	 * Get description
	 *
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set description
	 *
	 * @param  string $description
	 * @return Ticket
	 */
	public function setDescription($description)
	{
		$this->description = $description;
		
		return $this;
	}	
    

	
	/**
	 * Get priority
	 *
	 * @return string
	 */
	public function getPriority()
	{
		return $this->priority;
	}

	/**
	 * Set priority
	 *
	 * @param  string $priority
	 * @return Ticket
	 */
	public function setPriority($priority)
	{
		$this->priority = $priority;
		
		return $this;
	}	
    

	
	/**
	 * Get status
	 *
	 * @return string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set status
	 *
	 * @param  string $status
	 * @return Ticket
	 */
	public function setStatus($status)
	{
		$this->status = $status;
		
		return $this;
	}	
    

	
	/**
	 * Get recipient
	 *
	 * @return string
	 */
	public function getRecipient()
	{
		return $this->recipient;
	}

	/**
	 * Set recipient
	 *
	 * @param  string $recipient
	 * @return Ticket
	 */
	public function setRecipient($recipient)
	{
		$this->recipient = $recipient;
		
		return $this;
	}	
    

	
	/**
	 * Get requesterId
	 *
	 * @return integer
	 */
	public function getRequesterId()
	{
		return $this->requesterId;
	}

	/**
	 * Set requesterId
	 *
	 * @param  integer $requesterId
	 * @return Ticket
	 */
	public function setRequesterId($requesterId)
	{
		$this->requesterId = $requesterId;
		
		return $this;
	}	
    

	
	/**
	 * Get submitterId
	 *
	 * @return integer
	 */
	public function getSubmitterId()
	{
		return $this->submitterId;
	}

	/**
	 * Set submitterId
	 *
	 * @param  integer $submitterId
	 * @return Ticket
	 */
	public function setSubmitterId($submitterId)
	{
		$this->submitterId = $submitterId;
		
		return $this;
	}	
    

	
	/**
	 * Get assigneeId
	 *
	 * @return integer
	 */
	public function getAssigneeId()
	{
		return $this->assigneeId;
	}

	/**
	 * Set assigneeId
	 *
	 * @param  integer $assigneeId
	 * @return Ticket
	 */
	public function setAssigneeId($assigneeId)
	{
		$this->assigneeId = $assigneeId;
		
		return $this;
	}	
    

	
	/**
	 * Get organizationId
	 *
	 * @return integer
	 */
	public function getOrganizationId()
	{
		return $this->organizationId;
	}

	/**
	 * Set organizationId
	 *
	 * @param  integer $organizationId
	 * @return Ticket
	 */
	public function setOrganizationId($organizationId)
	{
		$this->organizationId = $organizationId;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Ticket
	 */
	public function addCollaboratorIds($elem)
	{
		$this->collaboratorIds[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasCollaboratorIds($elem)
	{
		return in_array($elem, $this->collaboratorIds);
	}
	
	
	/**
	 * Get collaboratorIds
	 *
	 * @return Array
	 */
	public function getCollaboratorIds()
	{
		return $this->collaboratorIds;
	}

	/**
	 * Set collaboratorIds
	 *
	 * @param  Array $collaboratorIds
	 * @return Ticket
	 */
	public function setCollaboratorIds($collaboratorIds)
	{
		$this->collaboratorIds = $collaboratorIds;
		
		return $this;
	}	
    

	
	/**
	 * Get forumTopicId
	 *
	 * @return integer
	 */
	public function getForumTopicId()
	{
		return $this->forumTopicId;
	}

	/**
	 * Set forumTopicId
	 *
	 * @param  integer $forumTopicId
	 * @return Ticket
	 */
	public function setForumTopicId($forumTopicId)
	{
		$this->forumTopicId = $forumTopicId;
		
		return $this;
	}	
    

	
	/**
	 * Get problemId
	 *
	 * @return integer
	 */
	public function getProblemId()
	{
		return $this->problemId;
	}

	/**
	 * Set problemId
	 *
	 * @param  integer $problemId
	 * @return Ticket
	 */
	public function setProblemId($problemId)
	{
		$this->problemId = $problemId;
		
		return $this;
	}	
    

	
	/**
	 * Get hasIncidents
	 *
	 * @return blob
	 */
	public function getHasIncidents()
	{
		return $this->hasIncidents;
	}

	/**
	 * Set hasIncidents
	 *
	 * @param  blob $hasIncidents
	 * @return Ticket
	 */
	public function setHasIncidents($hasIncidents)
	{
		$this->hasIncidents = $hasIncidents;
		
		return $this;
	}	
    

	
	/**
	 * Get dueAt
	 *
	 * @return datetime
	 */
	public function getDueAt()
	{
		return $this->dueAt;
	}

	/**
	 * Set dueAt
	 *
	 * @param  datetime $dueAt
	 * @return Ticket
	 */
	public function setDueAt($dueAt)
	{
		$this->dueAt = $dueAt;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Ticket
	 */
	public function addTags($elem)
	{
		$this->tags[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasTags($elem)
	{
		return in_array($elem, $this->tags);
	}
	
	
	/**
	 * Get tags
	 *
	 * @return Array
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * Set tags
	 *
	 * @param  Array $tags
	 * @return Ticket
	 */
	public function setTags($tags)
	{
		$this->tags = $tags;
		
		return $this;
	}	
    

	
	/**
	 * Get via
	 *
	 * @return Object
	 */
	public function getVia()
	{
		return $this->via;
	}

	/**
	 * Set via
	 *
	 * @param  Object $via
	 * @return Ticket
	 */
	public function setVia($via)
	{
		$this->via = $via;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Ticket
	 */
	public function addCustomFields($elem)
	{
		$this->customFields[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasCustomFields($elem)
	{
		return in_array($elem, $this->customFields);
	}
	
	
	/**
	 * Get customFields
	 *
	 * @return Array
	 */
	public function getCustomFields()
	{
		return $this->customFields;
	}

	/**
	 * Set customFields
	 *
	 * @param  Array $customFields
	 * @return Ticket
	 */
	public function setCustomFields($customFields)
	{
		$this->customFields = $customFields;
		
		return $this;
	}	
    

	
	/**
	 * Get satisfactionRating
	 *
	 * @return Object
	 */
	public function getSatisfactionRating()
	{
		return $this->satisfactionRating;
	}

	/**
	 * Set satisfactionRating
	 *
	 * @param  Object $satisfactionRating
	 * @return Ticket
	 */
	public function setSatisfactionRating($satisfactionRating)
	{
		$this->satisfactionRating = $satisfactionRating;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Ticket
	 */
	public function addSharingAgreementIds($elem)
	{
		$this->sharingAgreementIds[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasSharingAgreementIds($elem)
	{
		return in_array($elem, $this->sharingAgreementIds);
	}
	
	
	/**
	 * Get sharingAgreementIds
	 *
	 * @return Array
	 */
	public function getSharingAgreementIds()
	{
		return $this->sharingAgreementIds;
	}

	/**
	 * Set sharingAgreementIds
	 *
	 * @param  Array $sharingAgreementIds
	 * @return Ticket
	 */
	public function setSharingAgreementIds($sharingAgreementIds)
	{
		$this->sharingAgreementIds = $sharingAgreementIds;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Ticket
	 */
	public function addFollowupIds($elem)
	{
		$this->followupIds[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasFollowupIds($elem)
	{
		return in_array($elem, $this->followupIds);
	}
	
	
	/**
	 * Get followupIds
	 *
	 * @return Array
	 */
	public function getFollowupIds()
	{
		return $this->followupIds;
	}

	/**
	 * Set followupIds
	 *
	 * @param  Array $followupIds
	 * @return Ticket
	 */
	public function setFollowupIds($followupIds)
	{
		$this->followupIds = $followupIds;
		
		return $this;
	}	
    

	
	/**
	 * Get ticketFormId
	 *
	 * @return integer
	 */
	public function getTicketFormId()
	{
		return $this->ticketFormId;
	}

	/**
	 * Set ticketFormId
	 *
	 * @param  integer $ticketFormId
	 * @return Ticket
	 */
	public function setTicketFormId($ticketFormId)
	{
		$this->ticketFormId = $ticketFormId;
		
		return $this;
	}	
    

	
	/**
	 * Get brandId
	 *
	 * @return integer
	 */
	public function getBrandId()
	{
		return $this->brandId;
	}

	/**
	 * Set brandId
	 *
	 * @param  integer $brandId
	 * @return Ticket
	 */
	public function setBrandId($brandId)
	{
		$this->brandId = $brandId;
		
		return $this;
	}	
    

	
	/**
	 * Get allowChannelback
	 *
	 * @return blob
	 */
	public function getAllowChannelback()
	{
		return $this->allowChannelback;
	}

	/**
	 * Set allowChannelback
	 *
	 * @param  blob $allowChannelback
	 * @return Ticket
	 */
	public function setAllowChannelback($allowChannelback)
	{
		$this->allowChannelback = $allowChannelback;
		
		return $this;
	}	
    

	
	/**
	 * Get isPublic
	 *
	 * @return blob
	 */
	public function getIsPublic()
	{
		return $this->isPublic;
	}

	/**
	 * Set isPublic
	 *
	 * @param  blob $isPublic
	 * @return Ticket
	 */
	public function setIsPublic($isPublic)
	{
		$this->isPublic = $isPublic;
		
		return $this;
	}	
    

	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return Ticket
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return Ticket
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return Ticket
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
}