<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace ZendeskBundle\Entity\Definition;

/**
 * Definition class for the UserField connector object
 *
 */
trait UserFieldDefinition
{    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $key;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $type;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $title;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $rawTitle;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $description;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $rawDescription;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $position;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $active;
	
    

	 /**
	 * @var blob
	 *
	 
	 */
	
	private $system;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $regexpForValidation;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $createdAt;
	
    

	 /**
	 * @var datetime
	 *
	 
	 */
	
	private $updatedAt;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $tag;
	
    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $customFieldOptions;
	
    

	 /**
	 * @var integer
	 *
	 
	 */
	
	private $id;
	
    

	 /**
	 * @var string
	 *
	 
	 */
	
	private $url;
	
    

	
	/**
	 * Get key
	 *
	 * @return string
	 */
	public function getKey()
	{
		return $this->key;
	}

	/**
	 * Set key
	 *
	 * @param  string $key
	 * @return UserField
	 */
	public function setKey($key)
	{
		$this->key = $key;
		
		return $this;
	}	
    

	
	/**
	 * Get type
	 *
	 * @return string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Set type
	 *
	 * @param  string $type
	 * @return UserField
	 */
	public function setType($type)
	{
		$this->type = $type;
		
		return $this;
	}	
    

	
	/**
	 * Get title
	 *
	 * @return string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Set title
	 *
	 * @param  string $title
	 * @return UserField
	 */
	public function setTitle($title)
	{
		$this->title = $title;
		
		return $this;
	}	
    

	
	/**
	 * Get rawTitle
	 *
	 * @return string
	 */
	public function getRawTitle()
	{
		return $this->rawTitle;
	}

	/**
	 * Set rawTitle
	 *
	 * @param  string $rawTitle
	 * @return UserField
	 */
	public function setRawTitle($rawTitle)
	{
		$this->rawTitle = $rawTitle;
		
		return $this;
	}	
    

	
	/**
	 * Get description
	 *
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set description
	 *
	 * @param  string $description
	 * @return UserField
	 */
	public function setDescription($description)
	{
		$this->description = $description;
		
		return $this;
	}	
    

	
	/**
	 * Get rawDescription
	 *
	 * @return string
	 */
	public function getRawDescription()
	{
		return $this->rawDescription;
	}

	/**
	 * Set rawDescription
	 *
	 * @param  string $rawDescription
	 * @return UserField
	 */
	public function setRawDescription($rawDescription)
	{
		$this->rawDescription = $rawDescription;
		
		return $this;
	}	
    

	
	/**
	 * Get position
	 *
	 * @return integer
	 */
	public function getPosition()
	{
		return $this->position;
	}

	/**
	 * Set position
	 *
	 * @param  integer $position
	 * @return UserField
	 */
	public function setPosition($position)
	{
		$this->position = $position;
		
		return $this;
	}	
    

	
	/**
	 * Get active
	 *
	 * @return blob
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Set active
	 *
	 * @param  blob $active
	 * @return UserField
	 */
	public function setActive($active)
	{
		$this->active = $active;
		
		return $this;
	}	
    

	
	/**
	 * Get system
	 *
	 * @return blob
	 */
	public function getSystem()
	{
		return $this->system;
	}

	/**
	 * Set system
	 *
	 * @param  blob $system
	 * @return UserField
	 */
	public function setSystem($system)
	{
		$this->system = $system;
		
		return $this;
	}	
    

	
	/**
	 * Get regexpForValidation
	 *
	 * @return string
	 */
	public function getRegexpForValidation()
	{
		return $this->regexpForValidation;
	}

	/**
	 * Set regexpForValidation
	 *
	 * @param  string $regexpForValidation
	 * @return UserField
	 */
	public function setRegexpForValidation($regexpForValidation)
	{
		$this->regexpForValidation = $regexpForValidation;
		
		return $this;
	}	
    

	
	/**
	 * Get createdAt
	 *
	 * @return datetime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Set createdAt
	 *
	 * @param  datetime $createdAt
	 * @return UserField
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
		
		return $this;
	}	
    

	
	/**
	 * Get updatedAt
	 *
	 * @return datetime
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Set updatedAt
	 *
	 * @param  datetime $updatedAt
	 * @return UserField
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;
		
		return $this;
	}	
    

	
	/**
	 * Get tag
	 *
	 * @return string
	 */
	public function getTag()
	{
		return $this->tag;
	}

	/**
	 * Set tag
	 *
	 * @param  string $tag
	 * @return UserField
	 */
	public function setTag($tag)
	{
		$this->tag = $tag;
		
		return $this;
	}	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return UserField
	 */
	public function addCustomFieldOptions($elem)
	{
		$this->customFieldOptions[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasCustomFieldOptions($elem)
	{
		return in_array($elem, $this->customFieldOptions);
	}
	
	
	/**
	 * Get customFieldOptions
	 *
	 * @return Array
	 */
	public function getCustomFieldOptions()
	{
		return $this->customFieldOptions;
	}

	/**
	 * Set customFieldOptions
	 *
	 * @param  Array $customFieldOptions
	 * @return UserField
	 */
	public function setCustomFieldOptions($customFieldOptions)
	{
		$this->customFieldOptions = $customFieldOptions;
		
		return $this;
	}	
    

	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set id
	 *
	 * @param  integer $id
	 * @return UserField
	 */
	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}	
    

	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set url
	 *
	 * @param  string $url
	 * @return UserField
	 */
	public function setUrl($url)
	{
		$this->url = $url;
		
		return $this;
	}	
}